// <auto-generated />
using System;
using FinalProject_TreonZT.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalProjectTreonZT.Migrations
{
    [DbContext(typeof(GameContext))]
    partial class GameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinalProject_TreonZT.Models.Game", b =>
                {
                    b.Property<int?>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("GameId"));

                    b.Property<string>("Against")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("AwayScore")
                        .HasColumnType("int");

                    b.Property<int>("Date")
                        .HasColumnType("int");

                    b.Property<int?>("Goals")
                        .HasColumnType("int");

                    b.Property<int?>("HomeScore")
                        .HasColumnType("int");

                    b.Property<string>("Outcome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GameId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameId = 1,
                            Against = "Chaos Delta",
                            Assists = 0,
                            AwayScore = 3,
                            Date = 0,
                            Goals = 1,
                            HomeScore = 2,
                            Outcome = "Loss",
                            Position = "Center"
                        },
                        new
                        {
                            GameId = 2,
                            Against = "Brewmasters",
                            Assists = 0,
                            AwayScore = 4,
                            Date = 0,
                            Goals = 0,
                            HomeScore = 2,
                            Outcome = "Loss",
                            Position = "Center"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
